export const CATEGORIAS_RESIDENCIAS = {
  formalizacion: 'FORMALIZACIÓN',
  dialogo: 'DIÁLOGO COMUNIDAD LOCAL Y NUEVOS PÚBLICOS',
  asociativismo: 'ASOCIATIVISMO',
  compromiso: 'COMPROMISO CON EL MEDIO AMBIENTE'
};

export const CATEGORIAS_RESIDENTES = {
  vinculacion: 'VINCULACIÓN LOCAL',
  conciencia: 'CONCIENCIA AMBIENTAL',
  trabajo: 'TRABAJO CON NIÑEZ Y ADOLESCENCIA',
  impacto: 'IMPACTO EN LA CARRERA DEL ARTISTA'
}